server:
    port: 8080


dubbo:
    application:
        name: server-consumer
    base-backage: com.example.demo # dubbo服务调用者所在的包
    registry:
        address: 39.105.95.181
        port: 2181
        protocol: zookeeper
        subscribe: true
    protocol:
        name: dubbo
        host: 192.168.0.116
    consumer:
        timeout: 1000
        check: false  # 服务启动时检查被调用服务是否可用
        retries: 2    # 服务调用重试次数

spring:
    rabbitmq:
        host: 39.105.95.181
        port: 5672
        username: zyx
        password: zyx124272
        publisher-returns: true
        publisher-confirms: true
        template:
            mandatory: true  #当mandatory标志位设置为true时，如果exchange根据自身类型和消息routeKey无法找到一个符合条件的queue，那么会调用basic.return方法将消息返还给生产者；当mandatory设为false时，出现上述情形broker会直接将消息扔掉。
        listener:
            simple:
                max-concurrency: 2 #最大线程监听数
                concurrency: 2  #最小线程监听数
            direct:
                prefetch: 0 #当prefetch=0是，表示consumer将使用PULL(拉取)的方式从broker端获取消息
    datasource:
        db1:
            jdbc-url: jdbc:mysql://39.105.95.181:3306/thunder?useUnicode=true&amp
            driverClassName: com.mysql.jdbc.Driver
            username: root
            password: Zyx124272
        db2:
            jdbc-url: jdbc:mysql://localhost:3306/testQCC?useUnicode=true&amp
            driverClassName: com.mysql.jdbc.Driver
            username: root
            password: 123456

rocketmq:
    name-server: 39.105.95.181:9876
    producer:
        group: tansaction-group1

mybatis:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#    type-aliases-package: com.example.demo
#    mapper-locations: classpath*:mapper/*.xml
