server:
  port: 8081

dubbo:
  application:
    name: service-provider
  base-package: com.example.demo # dubbo服务发布者所在的包
  registry:
    address: 39.105.95.181 # zookeeper注册中心的地址
    port: 2181       # zookeeper注册中心的端口
    protocol: zookeeper
    register: true
  protocol:
    name: dubbo
    port: 20880
    accesslog: true
  provider:
    retries: 1
    delay: -1